/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as DeployNewTokenScriptJson } from "../DeployNewToken.ral.json";

export const DeployNewToken = new ExecutableScript<{
  templateId: HexString;
  name: HexString;
  symbol: HexString;
  decimals: bigint;
  initialSupply: bigint;
  uiFee: bigint;
}>(Script.fromJson(DeployNewTokenScriptJson, ""));
